//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Resources.Template {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Create {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Capstone.Resources.Views.Template.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        internal static string QuestionDescription {
            get {
                return ResourceManager.GetString("QuestionDescription", resourceCulture);
            }
        }
        
        internal static string ShowInResults {
            get {
                return ResourceManager.GetString("ShowInResults", resourceCulture);
            }
        }
        
        internal static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        internal static string SelectTag {
            get {
                return ResourceManager.GetString("SelectTag", resourceCulture);
            }
        }
        
        internal static string SelectTopic {
            get {
                return ResourceManager.GetString("SelectTopic", resourceCulture);
            }
        }
        
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        internal static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        internal static string restricted {
            get {
                return ResourceManager.GetString("restricted", resourceCulture);
            }
        }
    }
}
